### ISSUE TITLE
Processing obfuscated code

### ISSUE THREAD

**Issue by undavide** [ExtendScript/extendscriptr#23]
Hi,
I'm doing what you could easily call stress-tests on extendscriptr :-) Let me explain first what I'm after – if you think this kind of discussion is better done elsewhere feel free to move this one where it should more appropriately belong.

Since JsxBin, how can I put it, may not be anymore as sealed as we used to think, I'm trying to find alternatives. JS Obfuscators are either scams (introducing unwanted http requests) or too aggressive to the ESTK taste, so the obfuscated code doesn't work at all when run, say, in Photoshop. Known fact that [I proved years ago](http://www.davidebarranca.com/2013/08/testing-minified-js-libraries-in-extendscript/). Currently I'm testing [javascriptobfuscator](https://javascriptobfuscator.com/) (free tier, the paid options are too much for my needs) and [javascript2img](http://javascript2img.com/). FYI, I've discarded [Dan's Tools](http://www.danstools.com/javascript-obfuscate/index.php) for their obfuscated code is perfectly de-obfuscated by their own Beautifier - good job :-)
Then there is Marc Autret JsxBlind.

Results vary, also depending on the source code itself – I'm planning to write an extensive article as soon as I've gathered enough data.

My possibly weird idea is to extendscriptr-ize the obfuscated code (that might rely on some ES5/6 unsupported features) hoping that Photoshop will like it better.

No way so far! Errors spring on javascript2img code for instance (the one I personally find the best obfuscation result ever), while less aggressive options for javascriptobfuscator work out of the box without the need to be extendscriptr-ized.

Suggestions / thoughts?
I've also tried to just manually prepend the Array shims that extendscriptr seems to add to the code, with no luck – apparently javascript2img code is plain indigestible. There is any other secret sauce that extendscriptr adds, that I can add myself manually if the CLI doesn't work?
Thanks guys!!

Davide

**Comment by fabiantheblind** [comment]
Hi Davide,

the secret sauce to make this all work is to prepend the prototypes before anything else. Even before Browserify. It needs for example the https://github.com/fabiantheblind/extendscript.prototypes/blob/master/src/Object.defineProperty.js to make this work.  

Did you try to use a higher Node.js version with npm greater then 3.0?

**Comment by undavide** [comment]
Hello Fabian,
I'm currently using Node v6.3.0 and npm 3.10.3. Have you tried to obfuscate your own code with  javascript2img? javascriptobfuscator is driving me mad, some things work, other don't.
Sad business :-)
Thank you!

**Comment by fabiantheblind** [comment]
No I never tried. I'm totally in ❤️  with open source. Never tried one of these. Did extendscriptr work with your Node 6.3?

**Comment by undavide** [comment]
So far my tests with Node 6.3 and extendscriptr 1.0.3 (globally installed) are still failing, but local installation is OK!
Also, Node-latest is outputting no warnings anymore when installing it, which is a good news.

If I may ask here, what is browserify for, in extendscriptr? Aren't the prepended proto enough, or you need to "massage" the code in some other way afterwards? Thanks!

**Comment by fabiantheblind** [comment]
We use browserify to have the require magic available. If not we would have to implement all that file loading by ourselves. Can you paste the error that occurs with extendscript rad global module or better open an issue for that. Would be awesome

**Comment by fabiantheblind** [comment]
We use browserify to have the require magic available. If not we would have to implement all that file loading by ourselves. Can you paste the error that occurs with extendscript rad global module or better open an issue for that. Would be awesome

**Comment by undavide** [comment]
I'll keep using the other thread that I opened yesterday. If someone would like to try obfuscation I'll be happy to discuss the results. Thanks!

**Comment by fabiantheblind** [comment]
Looking forward to your article about it.
