### ISSUE TITLE
Use extendscript-es5-shim

### ISSUE THREAD

**Issue by fabianmoronzirfas** [ExtendScript/extendscriptr#24]
We should move ASAP from https://github.com/fabianmoronzirfas/extendscript.prototypes to https://github.com/ExtendScript/extendscript-es5-shim as soon as it is set up

**Comment by vogelino** [comment]
I agree with that! Having everything under the @ExtendScript organization is a good idea!

**Comment by fabianmoronzirfas** [comment]
Finally this can be closed. Thanks to @lumenn
