### ISSUE TITLE
Handle # statements

### ISSUE THREAD

**Issue by andyinabox** [ExtendScript/extendscriptr#28]
It would be nice if there was some way of addressing `#target`, `#include`, and maybe even `#includepath` here. Currently extendscriptr blows up when any of these are encountered.

A short-term fix would be to just ignore them, but it would be nice if `#include` could be translated to `import`. Not quite sure how `#includepath` would be best handled.

I came across this attempting to use extendscriptr with [basil.js](basiljs.ch), it fails because of a single `#target` statement in the basil.js file.

**Comment by andyinabox** [comment]
Seems like a babel transform might be a good way to handle this, but it's a bit daunting after scanning through the [babel plugin handbook](https://github.com/thejameskyle/babel-handbook/blob/master/translations/en/plugin-handbook.md)...

**Comment by fabianmoronzirfas** [comment]
Can you try to use the 

//@include Path/to/file.js

Syntax?

**Comment by fabianmoronzirfas** [comment]
@andyinabox BTW the latest Basil version is portable. You can place it where you want and don't need the includepath anymore. Also we suggest to move to the @include syntax. The # breaks linters as well.  

I will try to take a look into it ASAP. Currently I'm on mobile only.

**Comment by andyinabox** [comment]
Oh ok, yes thanks. I didn't know about the `//@include` syntax, so I'll try that.

**Comment by fabianmoronzirfas** [comment]
Yeah its only documented in the JavaScript Tools Guide I think.

**Comment by fabianmoronzirfas** [comment]
I created a PR on Basil to address this issue. We have been talking a long time about this in the Basil issues. Time to do it. :)

**Comment by andyinabox** [comment]
:+1: yeah!

**Comment by fabianmoronzirfas** [comment]
The changes I made are merged into the develop branch of Basil. We will merge into master soon 

All examples scripts PR https://github.com/basiljs/basil.js/pull/150
