### ISSUE TITLE
Watch mode

### ISSUE THREAD

**Issue by andyinabox** [ExtendScript/extendscriptr#31]
Not sayin' this necessarily needs to be built into extendscriptr, but even examples of a watch workflow would be helpful.

**Comment by fabianmoronzirfas** [comment]
Hi @andyinabox 
Over at basil.js we are using the [watch](https://github.com/mikeal/watch) module. Works good for us.  

    # install it as dev dependency
    npm install watch -D
    # run it in a terminal session
    # anytime you save your src/helloWorld.js
    it will be extendscriptred (is that a word yet? ;-))
    ./node_modules/.bin/watch ./node_modules/.bin/extendscriptr --script src/helloWorld.js --output dist/helloWord.js

**Comment by fabianmoronzirfas** [comment]
I'll keep this issue open until I (or somebody else) adds something useful about it to the readme

**Comment by florianbepunkt** [comment]
how can this be dynamic? watch looks for changes in the whole src folder, but the command provided in readme is fixed to a specific file.

if you have multiple scripts in src folder how can this be configured to compile each file when a change occurs?

**Comment by fabianmoronzirfas** [comment]
Hm. This wont work with the current state of extendsciptr. It would mean to do changes on the module. Would be nice to have. I'll add this as a new issue and feature request.
