### ISSUE TITLE
Feedback (and/or) extension

### ISSUE THREAD

**Issue by Lucassifoni** [ExtendScript/extendscriptr#34]
Hey, I'll need to use this extensively in inDesign for the 6 next months.
Would you be interested in a detailed weekly or monthly feedback as I'm progressing ?

**Comment by fabianmoronzirfas** [comment]
Yes of course. Monthly is good weekly even better.

**Comment by Lucassifoni** [comment]
Hi, I'm closing this, since we moved to using the Adobe Node.js bridge for this project, and I just saw I didn't give any news about this.. Sorry about that.
