### ISSUE TITLE
The future

### ISSUE THREAD

**Issue by GitBruno** [ExtendScript/extendscriptr#37]
Hey guys, I really like what you have done with extendscriptr and it is amazing it took me so long to find/use it.

I like the general setup but now we have [typescript](http://www.typescriptlang.org/) I personally would like to use that.

Not sure if that fits in this repo, as not all users might want to use typescript. Therefore it might be better to start a new sister project called typescriptr

Do you have any thoughts on this?

**Comment by fabianmoronzirfas** [comment]
Well it could have a `-t --typescript` flag.

**Comment by GitBruno** [comment]
That is a great idea! Will look into that.

Also do you want to update the babel preset from "es2015" to "extendscript" (`babel-preset-es2015` -> `babel-preset-extendscript`)?

**Comment by GitBruno** [comment]
seems to be taken by target engine `-t, --target`

What about:

    .option('-ts, --typescript', 'typescript mode')

**Comment by fabianmoronzirfas** [comment]
Fine with me. :-)

**Comment by GitBruno** [comment]
Cool, also `-nf --nofills` would be good as I like to roll my own sometimes.

Might be nice to require extendscript-bundlr here as well? `-b --bundle`

**Comment by danielbayley** [comment]
If extendscriptr could accept stdin, then _any_ transpiler language could be used… not just Typescript (CoffeeScript for example)…

Something like: `coffee --print *.coffee | extendscriptr --script -` (or `--stdin`, or maybe just accept stdin if no `--script` is passed)?

**Comment by fabianmoronzirfas** [comment]
@danielbayley great idea. Can you write something?

**Comment by fabianmoronzirfas** [comment]
@GitBruno is this still a thing?

**Comment by fabianmoronzirfas** [comment]
@GitBruno ping? Is this still a thing?

**Comment by GitBruno** [comment]
Nope :)
