### ISSUE TITLE
Global install still not working

### ISSUE THREAD

**Issue by fabianmoronzirfas** [ExtendScript/extendscriptr#38]

**Comment by fabianmoronzirfas** [comment]
Issue #45 is created by the package add-local-binaries-to-path. This only works in unix environments. I also dislike that it edits the users environment without telling something about it in the README. I will remove it.

**Comment by fabianmoronzirfas** [comment]
I installed it globally and it works without that package.

**Comment by GitBruno** [comment]
Did you remove these lines from your `.bashProfile` when testing?

    # added by `npm i -g add-local-binaries-to-path`
    export PATH="$PATH:./node_modules/.bin"

**Comment by GitBruno** [comment]
Yeah, it as all good. Sorry for the headache, I think my tests where running in a seperate env :) Taking global a little too serious!
