### ISSUE TITLE
Test in Illustrator

### ISSUE THREAD

**Issue by ff6347** [ExtendScript/extendscriptr#4]

**Comment by fabiantheblind** [comment]
Some input on illustrator https://github.com/jtnimoy/scripting-for-illustrator-tutorial

**Comment by mhulse** [comment]
My focus has been on Illustrator scripting ... I think I can help with this over the coming weeks. Any suggestions on testing? Anything in particular I should look out for, or is it just to generally test in Illustrator to see how it handles various features es5 and es6 in an es3 environ?

I do see there's already a test script here:

https://github.com/ExtendScript/extendscriptr/blob/f778e762428362dbf4a8f6a615ceeadd5d50a5c6/test/src/illustrator.js

I'm new t o extendscriptr, but definitely interested in helping.

**Comment by fabiantheblind** [comment]
@mhulse Thanks for offering your help. It has been getting a bit quite around here. :-)

We need testing for:  

extendscript specific features like:

    File, Folder, $ and so on

and of course some more complex scritps like the first test we have.

On the JS side there is a lot to be done.
Maybe we should take this table as basic for things we want to test --> http://kangax.github.io/compat-table/es6/  

Actually every ES6 feature needs to be tested. For now we only have import and template strings in there. I would start with:  

    let, const, () => {}, argument defaults…

**Comment by mhulse** [comment]
Awesome! Sounds good! I'll put this on my list of projects to tackle over the coming weeks! 👍 

Thanks for the quick reply and details @fabiantheblind!

**Comment by fabiantheblind** [comment]
Awesome looking forward to some contributions. Do you want to make a fork of the repo or work on another branch in here?

**Comment by fabiantheblind** [comment]
@mhulse added you to a team. Please don't merge right away.
- Create a branch
- push to it
- make a PR against master
- assign me for review

**Comment by kostimarko** [comment]
```var destFolder, sourceFolder, files, fileType, sourceDoc, targetFile, epsSaveOpts, doc;

sourceFolder = Folder.selectDialog( 'Select the folder with Illustrator files you want to convert to png', '~' );

if ( sourceFolder != null )
{
  files = new Array();
	fileType = "*.ai";
	
	// Get all files matching the pattern
	files = sourceFolder.getFiles( fileType );
	
	if ( files.length > 0 )
	{
		// Get the destination to save the files
		destFolder = Folder.selectDialog( 'Select the folder where you want to save the converted png files.', '~' );
		for ( i = 0; i < files.length; i++ )
		{
            sourceDoc = app.open(files[i]); // returns the document object
            doc = app.activeDocument;
            doc.layers.forEach((layer)=>{
                doc.layers[layer].visible=true;
            })

			//sourceDoc.close(SaveOptions.DONOTSAVECHANGES);
		}
		alert( 'Files are saved as EPS in ' + destFolder );
	}
	else
	{
		alert( 'No matching files found' );
	}
}```

when Illustrator runs this script after compiling , I get this error.
![Screen Shot 2019-03-14 at 9 45 32 AM](https://user-images.githubusercontent.com/7833020/54366046-efb3d400-463d-11e9-9e9c-258cc921cb21.png)

**Comment by fabianmoronzirfas** [comment]
Hi @kostimarko would be good to open a separate issue for that. I don't have Illustrator currently installed so I can't test it right away. My guess is:

The object `document.layer` is not a normal Javascript array. It is a collection object which has some overlapping properties with the JS Array. If you can run a test that shows that `forEach` is actually not working we can investigate more.

**Comment by kostimarko** [comment]
@fabianmoronzirfas you're correct. It is not an array. Sorry about that.

**Comment by fabianmoronzirfas** [comment]
@kostimarko No problemo.
