### ISSUE TITLE
npm ERR! code ELIFECYCLE npm ERR! errno 1 on npm install

### ISSUE THREAD

**Issue by Misterdudeman** [ExtendScript/extendscriptr#45]
Hey guys, I have been trying to install ExtendScriptr but can't quite figure out what is going wrong with this. Most likely just me doing it wrong but you never know.

npm install extendscriptr --save-dev

> add-local-binaries-to-path@1.1.3 postinstall D:\PROGRAMMING\PROJECTS\VECTOR_OPS\node_modules\add-local-binaries-to-path
> node index.js

Could not find any config files for bash, fish, or zsh!
npm WARN vector_ops@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! add-local-binaries-to-path@1.1.3 postinstall: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the add-local-binaries-to-path@1.1.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ian\AppData\Roaming\npm-cache\_logs\2018-07-21T08_22_47_330Z-debug.log

**Comment by fabianmoronzirfas** [comment]
Thanks @Misterdudeman I removed the package "add-local-binaries-to-path" this only works on unix machines. 

If you install the latest version it  should work.
Thanks for reporting the issue.
