### ISSUE TITLE
extendscriptr: command not found

### ISSUE THREAD

**Issue by kostimarko** [ExtendScript/extendscriptr#47]
I've installed the library, but every time I try to run `extendscriptr --script src/Layers_To_PNG.js --output dist/Layer_To_PNG_v2.jsx` I get `extendscriptr: command not found`

node: 8.11.3
npm: 5.6.0

What am I doing wrong?

**Comment by kostimarko** [comment]
I didn't install the library globally, after installing it globally it works

**Comment by fabianmoronzirfas** [comment]
I suggest not to install node_modules globally. When you install it locally you can add it to a npm script
package.json
```json
{
 "scripts":{
 "build": "extendscriptr --script src/Layers_To_PNG.js --output 
 dist/Layer_To_PNG_v2.jsx"
 }
}
```

and run it with `npm run build`
