### ISSUE TITLE
Export as node module

### ISSUE THREAD

**Issue by vogelino** [ExtendScript/extendscriptr#7]
`npm publish`

crate new account on https://www.npmjs.com/

Follow the steps here:
https://medium.com/@jdaudier/how-to-create-and-publish-your-first-node-js-module-444e7585b738#.mo2f6tz3s

**Comment by fabiantheblind** [comment]
😆

**Comment by vogelino** [comment]
Created a npm account: https://www.npmjs.com/~vogelino#user-info-menu

**Comment by vogelino** [comment]
https://www.npmjs.com/package/extendscriptr
